### PR TITLE
Fix dependabot config file to reference multiple directories

### PR DESCRIPTION
**Pull request by mikealfare**
The `directory` attribute is not recursive, and cannot take a list. An entry is needed for each directory.

### CODE REVIEW

**Review by emmyoop — APPROVED** [review]
Change looks good even though tests are failing?

**Comment by mikealfare** [comment]
> Change looks good even though tests are failing?

Yeah, I think we're failing on `main`. I thought the issue was related to `psycopg2` on `dbt-postgres`, but it might be something else. I need to look at it.

**Comment by mikealfare** [comment]
Relevant logs:
```


Checking psycopg2 install...psycopg2-binary==2.9.9
ok
Checking psycopg2-binary...psycopg2-binary==2.9.9
psycopg2-binary is installed and should not be!
```

**Comment by mikealfare** [comment]
This is failing on API rate limiting again, which is a known issue.

**Pull request merged**
