### PR TITLE
Add dbt-synapse 1.7.0rc1 to the 1.7 pre-release bundle

### PR DESCRIPTION
**Pull request by mikealfare**
`dbt-synapse` has a 1.7 pre-release available. This adds the pre-release to the pre-release bundle. `dbt-synapse` has not published a final release yet.

### CODE REVIEW

**Comment by mikealfare** [comment]
This appears to be happening somewhere:
```
ERROR: dbt-postgres from git+https://github.com/dbt-labs/dbt-core.git@main#egg=dbt-postgres&subdirectory=plugins/postgres (from -r /Users/runner/work/dbt-core-bundles/dbt-core-bundles/release_creation/bundle/requirements/v0.0.latest.requirements.txt (line 2)) does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
```
This doesn't exist on `main`. Since this is the 1.7 bundle, this should probably be `@1.7.latest` instead of `@main`.

**Comment by mikealfare** [comment]
We're hitting rate limit errors, which we've seen in the past. Once run did succeed though, suggesting this is a viable bundle. I'll rerun other versions (in particular py38) if they fail.

**Comment by mikealfare** [comment]
py311 passed for ubuntu, rerunning for macos. Older versions of python are failing due to dependency conflicts involving hatching. It seems like there are a combination of dependencies that make this require py311, which is not consistent with our support (py38+).

**Comment by colin-rogers-dbt** [comment]
@mikealfare added hatch and dbt-common/dbt-adapters to the dev requirements, looks like it's passing now

**Review by colin-rogers-dbt — APPROVED** [review]

**Pull request merged**
